name: "🐛 Bug Report" 
description: "Report a bug or issue with the Rise Gaming Takistan Life server"
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Please provide detailed information to help us reproduce and fix the issue.
  
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm before submitting
      options:
        - label: I have searched existing issues to ensure this hasn't been reported
          required: true
        - label: This is a legitimate bug that affects normal gameplay
          required: true
  
  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: A clear, concise description of the bug
      placeholder: "e.g., Vehicle spawns underground at checkpoint"
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Clear steps to reproduce the issue
      placeholder: |
        1. Go to...
        2. Click on...
        3. Perform action...
        4. Observe error
    validations:
      required: true
  
  - type: input
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: "The vehicle should spawn correctly on the surface"
    validations:
      required: true
  
  - type: input
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Vehicle spawned partially underground"
    validations:
      required: true
  
  - type: dropdown
    id: faction
    attributes:
      label: Affected Faction
      description: Which faction experiences this bug?
      options:
        - "Civilian"
        - "Police/NATO"
        - "Insurgent"
        - "OPFOR/TLA"
        - "ESU"
        - "PMC"
        - "All Factions"
        - "Administrative/Staff"
    validations:
      required: true
  
  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: Screenshots, videos, or log files (optional)
      placeholder: "Drag and drop files here or provide links..."
