name: "💡 General Suggestion"
description: "Share ideas for server improvements, events, or community enhancements"
title: "[SUGGESTION] "
labels: ["suggestion", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        ## General Suggestion
        Use this template for suggestions about server improvements, events, or community enhancements.
  
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm before submitting
      options:
        - label: I have searched existing issues to ensure this hasn't been suggested
          required: true
        - label: This suggestion aligns with the server's values
          required: true
  
  - type: dropdown
    id: category
    attributes:
      label: Suggestion Category
      description: What type of suggestion is this?
      options:
        - "Server Rules & Regulations"
        - "Community Events & Activities"
        - "Quality of Life Improvements"
        - "Economy & Balance"
        - "Administrative Processes"
        - "Other"
    validations:
      required: true
  
  - type: input
    id: title
    attributes:
      label: Suggestion Title
      description: A clear title for your suggestion
      placeholder: "e.g., Weekly community racing events"
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Explain your suggestion in detail
      placeholder: "Describe what you're suggesting and how it would work..."
    validations:
      required: true
  
  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What positive impacts would this have?
      placeholder: "This would improve the community by..."
    validations:
      required: true
  
  - type: dropdown
    id: scope
    attributes:
      label: Scope of Impact
      description: How broadly would this affect the community?
      options:
        - "Affects all players significantly"
        - "Affects most players moderately"
        - "Affects specific groups"
        - "Limited scope but important"
    validations:
      required: true
