blank_issues_enabled: false
contact_links:
  - name: 🎮 Join Our Discord Server
    url: https://discord.gg/dVWvxEZJBj
    about: Connect with the community and get real-time support
  - name: 📜 Server Rules & Guidelines
    url: https://github.com/RiseGaming/Takistan-Life-Rules
    about: Review our comprehensive server rules and community guidelines