name: 💡 General Suggestion
description: Share ideas for server improvements, events, or community enhancements
type: Suggestion
body:
  - type: markdown
    attributes:
      value: |
        ## General Suggestion

        Thank you for sharing your ideas! Use this template for suggestions about server improvements, community events, rule changes, or other enhancements that don't fit into specific feature requests.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed these steps before submitting
      options:
        - label: I have searched existing issues to ensure this suggestion hasn't been made
          required: true
        - label: I have read the server rules and community guidelines
          required: true
        - label: This suggestion aligns with the server's roleplay focus and community values
          required: true

  - type: dropdown
    id: suggestion-category
    attributes:
      label: Suggestion Category
      description: What type of suggestion is this?
      options:
        - Server Rules & Regulations
        - Community Events & Activities
        - Quality of Life Improvements
        - Server Performance & Stability
        - Player Onboarding & Training
        - Communication & Discord
        - Administrative Processes
        - Economy & Balance
        - Roleplay Guidelines
        - Other
    validations:
      required: true

  - type: input
    id: suggestion-title
    attributes:
      label: Suggestion Title
      description: A clear, concise title for your suggestion
      placeholder: "Weekly community events to boost engagement"
    validations:
      required: true

  - type: textarea
    id: current-situation
    attributes:
      label: Current Situation
      description: Describe how things work currently (if applicable)
      placeholder: |
        - What is the current state?
        - What challenges or limitations exist?
        - Why might this need improvement?
    validations:
      required: true

  - type: textarea
    id: proposed-improvement
    attributes:
      label: Proposed Improvement
      description: Detail your suggestion and how it would work
      placeholder: |
        - What exactly are you suggesting?
        - How would it be implemented?
        - What would change for players?
        - What would the process look like?
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What positive impacts would this suggestion have?
      placeholder: |
        - How would this improve the community?
        - What problems would it solve?
        - Who would benefit and how?
        - What outcomes do you expect?
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Scope of Impact
      description: How broadly would this suggestion affect the community?
      options:
        - Affects all players significantly
        - Affects most players moderately
        - Affects specific player groups
        - Primarily administrative/backend
        - Limited scope but important
    validations:
      required: true

  - type: dropdown
    id: implementation-difficulty
    attributes:
      label: Estimated Implementation Difficulty
      description: How complex do you think this would be to implement?
      options:
        - Simple - Could be done quickly with existing tools
        - Moderate - Would require some planning and coordination
        - Complex - Would need significant development or changes
        - Very Complex - Would require major system overhauls
        - Unknown - Not sure about technical requirements
    validations:
      required: true

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas (Optional)
      description: Any thoughts on how this could be implemented or rolled out?
      placeholder: |
        - Could start with a trial period...
        - Might require changes to...
        - Could be integrated with existing...
        - Suggest phased rollout approach...
    validations:
      required: false

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternative Solutions (Optional)
      description: Have you considered other ways to address this issue?
      placeholder: |
        - Other approaches that might work...
        - Simpler alternatives you've thought of...
        - Different solutions that address similar problems...
    validations:
      required: false

  - type: textarea
    id: community-feedback
    attributes:
      label: Community Feedback (Optional)
      description: Have you discussed this with other community members? What was their response?
      placeholder: |
        - Reactions from other players...
        - Support or concerns expressed...
        - Additional ideas from discussions...
        - Consensus or disagreements noted...
    validations:
      required: false

  - type: textarea
    id: examples-references
    attributes:
      label: Examples or References (Optional)
      description: References to similar implementations on other servers or communities
      placeholder: |
        - How [Community Name] handles this...
        - Reference links or examples...
        - Inspiration from other games/servers...
    validations:
      required: false

  - type: textarea
    id: success-metrics
    attributes:
      label: How Would We Measure Success? (Optional)
      description: How would we know if this suggestion is working well?
      placeholder: |
        - Increased player engagement...
        - Fewer complaints about...
        - Improved community satisfaction...
        - Measurable outcomes like...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be relevant
      placeholder: |
        - Background context for this suggestion...
        - Timing considerations...
        - Related ongoing discussions...
        - Any other relevant details...
    validations:
      required: false
